import photosJson from "@/content/photos.json";
import { series } from "@/content/series";

/**
 * One rendition of a photo at a given width. Paths are site-relative
 * (`/photos/<id>-960.avif`), generated by `npm run photos` (scripts/photos.ts).
 */
export interface Rendition {
  width: number;
  avif: string;
  jpg: string;
}

/**
 * The photo manifest entry. Generated from content/photos.csv + the originals
 * in photos/ by `npm run photos`; never hand-edited. This interface is the
 * contract between the pipeline (Phase 1) and the B pages (Phase 2).
 */
export interface Photo {
  /** Stable id: the CSV `file` without extension, slugified. */
  id: string;
  /** Original filename as listed in the CSV (for the strict file↔row check). */
  file: string;
  /** Intrinsic size of the original, for aspect ratio and next/image. */
  width: number;
  height: number;
  /** Renditions, ascending by width (e.g. 480, 960, 1600). */
  renditions: Rendition[];
  /** Tiny base64 JPEG for next/image `placeholder="blur"`. */
  blur: string;
  title: string;
  place: string;
  year: number;
  /** Must match a `slug` in content/series.ts. */
  series: string;
  /** Appears on the B home streams. */
  home: boolean;
  /** Sequence on the home; lower first. Set on covers of shoots with a home position. */
  order: number | null;
  /** 1-based position within its shoot (filename order). */
  rank: number | null;
  /** The shoot (session) slug; a single is a one-photo shoot named after its file. */
  shoot: string | null;
  /** The one photo per shoot the gallery shows as its cover (and the home pick). */
  cover: boolean;
  alt: string;
}

/** A gallery item: a shoot (cover + its photos, in order) or a single photo. */
export type GalleryItem =
  | { kind: "shoot"; slug: string; cover: Photo; photos: Photo[] }
  | { kind: "single"; photo: Photo };

const photos = photosJson as Photo[];

export function getAllPhotos(): Photo[] {
  return photos;
}

/** Home-page selection, in `order` (then year desc, then title). */
export function getHomePhotos(): Photo[] {
  return photos
    .filter((p) => p.home)
    .sort(
      (a, b) =>
        (a.order ?? 1e9) - (b.order ?? 1e9) ||
        b.year - a.year ||
        a.title.localeCompare(b.title),
    );
}

/**
 * Photos grouped by series slug, series order preserved. Within a series the
 * manifest order is kept: it is already shoot row order, then position in
 * the shoot (see scripts/photos.ts).
 */
export function getPhotosBySeries(): Map<string, Photo[]> {
  const map = new Map<string, Photo[]>();
  for (const s of series) map.set(s.slug, []);
  for (const p of photos) {
    if (!map.has(p.series)) map.set(p.series, []);
    map.get(p.series)!.push(p);
  }
  return map;
}

/** All photos of a shoot, in manifest (= gallery) order. */
export function getShootPhotos(slug: string): Photo[] {
  return photos.filter((p) => p.shoot === slug);
}

/**
 * Group an ordered photo list into gallery items: each shoot appears once,
 * at the position of its first photo, as a cover + set; the rest are singles.
 */
export function groupShoots(list: Photo[]): GalleryItem[] {
  const seen = new Set<string>();
  const items: GalleryItem[] = [];
  for (const p of list) {
    if (!p.shoot) {
      items.push({ kind: "single", photo: p });
      continue;
    }
    if (seen.has(p.shoot)) continue;
    seen.add(p.shoot);
    const set = list.filter((x) => x.shoot === p.shoot);
    items.push({ kind: "shoot", slug: p.shoot, cover: set.find((x) => x.cover) ?? set[0], photos: set });
  }
  return items;
}

export function getPhoto(id: string): Photo | undefined {
  return photos.find((p) => p.id === id);
}
