import photosJson from "@/content/photos.json";
import { series } from "@/content/series";

/**
 * One rendition of a photo at a given width. Paths are site-relative
 * (`/photos/<id>-960.avif`), generated by `npm run photos` (scripts/photos.ts).
 */
export interface Rendition {
  width: number;
  avif: string;
  jpg: string;
}

/**
 * The photo manifest entry. Generated from content/photos.csv + the originals
 * in photos/ by `npm run photos`; never hand-edited. This interface is the
 * contract between the pipeline (Phase 1) and the B pages (Phase 2).
 */
export interface Photo {
  /** Stable id: the CSV `file` without extension, slugified. */
  id: string;
  /** Original filename as listed in the CSV (for the strict file↔row check). */
  file: string;
  /** Intrinsic size of the original, for aspect ratio and next/image. */
  width: number;
  height: number;
  /** Renditions, ascending by width (e.g. 480, 960, 1600). */
  renditions: Rendition[];
  /** Tiny base64 JPEG for next/image `placeholder="blur"`. */
  blur: string;
  title: string;
  place: string;
  year: number;
  /** Must match a `slug` in content/series.ts. */
  series: string;
  /** Appears on the B home streams. */
  home: boolean;
  /** Sequence on the home; lower first. Ignored when `home` is false. */
  order: number | null;
  /**
   * Position within its series in the gallery; lower first, blank after all
   * ranked ones. Ties fall back to the filename in natural order, so a
   * 01-/02- prefix on the files is enough to order a shoot.
   */
  rank: number | null;
  alt: string;
}

const photos = photosJson as Photo[];

export function getAllPhotos(): Photo[] {
  return photos;
}

/** Home-page selection, in `order` (then year desc, then title). */
export function getHomePhotos(): Photo[] {
  return photos
    .filter((p) => p.home)
    .sort(
      (a, b) =>
        (a.order ?? 1e9) - (b.order ?? 1e9) ||
        b.year - a.year ||
        a.title.localeCompare(b.title),
    );
}

const natural = new Intl.Collator(undefined, { numeric: true, sensitivity: "base" });

/**
 * Photos grouped by series slug, series order preserved. Within a series:
 * rank (blank last), then filename in natural order, then newest first.
 */
export function getPhotosBySeries(): Map<string, Photo[]> {
  const map = new Map<string, Photo[]>();
  for (const s of series) map.set(s.slug, []);
  for (const p of photos) {
    if (!map.has(p.series)) map.set(p.series, []);
    map.get(p.series)!.push(p);
  }
  for (const list of map.values()) {
    list.sort(
      (a, b) =>
        (a.rank ?? 1e9) - (b.rank ?? 1e9) ||
        natural.compare(a.file, b.file) ||
        b.year - a.year,
    );
  }
  return map;
}

export function getPhoto(id: string): Photo | undefined {
  return photos.find((p) => p.id === id);
}
